### ISSUE TITLE
Punk 0 in retro set

### ISSUE THREAD

**Issue by RedNax67** [neptune2/EleksTube-IPS-Retro-Nixie-Digits#1]
Hi!  Great work!  Maybe there's alight differences in original dumps, because i'm getting a punk 0 in my retro set?

**Comment by neptune2** [comment]
Thanks!
Hmm..

I see all 21 digits in the same location in the firmware for all 3 versions I have.

I did the following to double check:
`dd if=fw-backup-4M.bin of=all.bin skip=$((0x15d9a8-21*64800)) count=$((270*5280)) iflag=skip_bytes,count_bytes
convert -size 135x5280 -depth 16 GRAY:all.bin all.png`

The all.png file is a grayscale image. 
'convert' is part of ImageMagick.

Is there a typo somewhere in this repo?

**Comment by RedNax67** [comment]
In the readme there's:

```
dd if=fw-backup-4M.bin of=retro.bin skip=$((0x15d9a8-10*64800)) count=$((270*2640)) iflag=skip_bytes,count_bytes
convert -size 135x2640 -depth 16 GRAY:retro.bin retro.png #The first digit is the punk 0

```
2640 == 11 * 240 images

so skip back one less and read only 10 images fixes it for me:
```

dd if=fw-backup-4M.bin of=retro.bin skip=$((0x15d9a8-9*64800)) count=$((270*2400)) iflag=skip_bytes,count_bytes
convert -size 135x2400 -depth 16 GRAY:retro.bin retro.png

```

Fun thing, pushimage is used in the drawbmp function after converting the bmp, so... i plan to upload the individual .bin files and just  push them to the  display when they fail teh bmp magic check

Get the individual bin's

```
for i in {0..9}
do
  dd if=fw-backup-4M.bin of=$i.bin skip=$((0x15d9a8-$i*64800)) count=$((270*240)) iflag=skip_bytes,count_bytes
  convert -size 135x240 -depth 16 GRAY:$i.bin $i.png # for reference, not using in elekstube code
done
```

Update: I've added support for these resulting bin files to my fork of WLED... Just upload them in the usual way. Remove the .bmp as they take precedence..

Update2: Support is now merged into the main WLED repository.

**Comment by neptune2** [comment]
Thanks @RedNax67. [README.md](https://github.com/neptune2/EleksTube-IPS-Retro-Nixie-Digits/blob/main/README.mdl) corrected
