### ISSUE TITLE
convert extracted bin to image files

### ISSUE THREAD

**Issue by falkenhawk** [neptune2/EleksTube-IPS-Retro-Nixie-Digits#2]
Hi,
would you have any tips for me how to convert extracted bin files into sets of individual bmp images?

**Comment by neptune2** [comment]
Here is one possible way:
ffmpeg -vcodec rawvideo -f rawvideo -pix_fmt rgb565 -s 135x240 -i img.bin -f image2 -vcodec mjpeg img.jpg

Then convert the jpg to bmp.

**Comment by neptune2** [comment]
closing issue
